"""Identification-aware causal inference and instrumental-variable workflows."""

from .crossfit import (
    CATEEstimatorProtocol,
    CATEResultProtocol,
    ClassProbabilityCrossFitResult,
    ClassProbabilityCrossFitTask,
    ClassProbabilityTaskCrossFitResult,
    CrossFitResult,
    CrossFitTask,
    CrossFitTaskResult,
    CrossFitter,
    NuisanceDiagnosticsProtocol,
    NuisanceEstimatorProtocol,
    OutcomeResultProtocol,
    PropensityResultProtocol,
    WeightedCATEEstimatorProtocol,
    WeightedNuisanceEstimatorProtocol,
)
from .diagnostics import FirstStageDiagnostic, SarganTest
from .did import (
    DiDHausmanDiagnostic,
    DiDPretrendDiagnostic,
    DiDResult,
    DifferenceInDifferences,
    EfficientDiD,
    did_hausman_test,
)
from .did_rcs import (
    RepeatedCrossSectionCompositionDiagnostic,
    RepeatedCrossSectionDiD,
    RepeatedCrossSectionDiDResult,
    RepeatedCrossSectionPretrendDiagnostic,
    RepeatedCrossSectionSurveyDesign,
    did_rcs_composition_test,
)
from .integrations import add_to_outputhub, to_outputhub_model
from .iv import IV2SLS, IV2SLSResult
from .matching import (
    FittedPropensityMLEProtocol,
    NearestNeighborMatch,
    NearestNeighborMatchResult,
    PropensityScoreStatus,
)
from .ml import (
    DRLearner,
    DRLearnerResult,
    NativeSplineRidgeCATE,
    NativeSplineRidgeCATEResult,
    PartiallyLinearDML,
    PartiallyLinearDMLResult,
    RLearner,
    RLearnerResult,
)
from .observational import AIPWATE, IPWATE, ObservationalATEResult, OverlapDiagnostic
from .postestimation import (
    confint,
    fitted_values,
    lincom,
    predict,
    residuals,
    summary_frame,
    vcov,
    wald_test,
)
from .randomized import CovariateBalance, RandomizedATE, RandomizedATEResult

__all__ = [
    "CATEEstimatorProtocol",
    "CATEResultProtocol",
    "FirstStageDiagnostic",
    "CovariateBalance",
    "ClassProbabilityCrossFitResult",
    "ClassProbabilityCrossFitTask",
    "ClassProbabilityTaskCrossFitResult",
    "CrossFitResult",
    "CrossFitTask",
    "CrossFitTaskResult",
    "CrossFitter",
    "DiDHausmanDiagnostic",
    "DiDPretrendDiagnostic",
    "DiDResult",
    "DifferenceInDifferences",
    "DRLearner",
    "DRLearnerResult",
    "EfficientDiD",
    "FittedPropensityMLEProtocol",
    "AIPWATE",
    "IV2SLS",
    "IV2SLSResult",
    "IPWATE",
    "ObservationalATEResult",
    "OverlapDiagnostic",
    "NuisanceEstimatorProtocol",
    "NuisanceDiagnosticsProtocol",
    "NearestNeighborMatch",
    "NearestNeighborMatchResult",
    "NativeSplineRidgeCATE",
    "NativeSplineRidgeCATEResult",
    "OutcomeResultProtocol",
    "PartiallyLinearDML",
    "PartiallyLinearDMLResult",
    "RLearner",
    "RLearnerResult",
    "RepeatedCrossSectionDiD",
    "RepeatedCrossSectionCompositionDiagnostic",
    "RepeatedCrossSectionDiDResult",
    "RepeatedCrossSectionPretrendDiagnostic",
    "RepeatedCrossSectionSurveyDesign",
    "PropensityResultProtocol",
    "PropensityScoreStatus",
    "WeightedCATEEstimatorProtocol",
    "WeightedNuisanceEstimatorProtocol",
    "SarganTest",
    "RandomizedATE",
    "RandomizedATEResult",
    "add_to_outputhub",
    "confint",
    "fitted_values",
    "lincom",
    "predict",
    "residuals",
    "summary_frame",
    "to_outputhub_model",
    "vcov",
    "wald_test",
    "did_hausman_test",
    "did_rcs_composition_test",
]

__version__ = "0.7.0a6"
